<a href="https://colab.research.google.com/github/nss075/proj_2/blob/main/MarksAdding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns                      
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/content/Mini Project - Marks Adding.csv") 
df.head()

    Roll Num  Marks
0  102003542      1
1  102003640      1
2  102003725      1
3  102003307      1
4  102003458      1

In [15]:
df['Sum'] = df.groupby(['Roll Num'])['Marks'].transform('sum')
print(df.drop_duplicates(subset=['Roll Num'],keep='last'))

       Roll Num  Marks  Sum  Total
299   102003633      1    3      3
486   102003421      1    2      2
517   102003582      1    1      1
597   102003432      1    3      3
605   102003711      1    5      5
...         ...    ...  ...    ...
1831  102003755      1    5      5
1832  102017147      1    5      5
1833  102017152      1    5      5
1834  102003451      1    5      5
1835  102003549      1    5      5

[400 rows x 4 columns]

    Roll Num  Marks  Sum  Total
0  102003542      1    4      4
1  102003640      1    5      5
2  102003725      1    5      5
3  102003307      1    4      4
4  102003458      1    5      5